version: '1.0'

services:
  api-server:
    build:
      context: ./server
      dockerfile: Dockerfile
    port:
      - "7231:7231"
    environment:
      - POSTGRES_URL=${POSTGRES_URL}
      - JWT_SECRET=${JWT_SECRET}
      - NODE_ENV=development
    volumes:
      # mount the code for live reloading
      - ./server:/app
      # Exclude node_moudle to use the ones installed in the container
      - /app/node_modules

  ml-server:
    build:
      context: ./ml
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - APP_HOST=0.0.0.0
      - APP_PORT=5000
    volumes:
      - ./ml:/app