version: '3.8'

services:
  api-server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "7231:7231"
    environment:
      - POSTGRES_URL=${POSTGRES_URL}
      - JWT_SECRET=${JWT_SECRET}
      - NODE_ENV=development
      - PORT=7231
      - HOST=${HOST}
      - JWT_EXPIRATION=${JWT_EXPIRATION}
      - CORS_ORIGIN=${CORS_ORIGIN}
      - LOG_LEVEL=info
    

  ml-server:
    build:
      context: ./ml
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - APP_HOST=0.0.0.0
      - APP_PORT=5000
    